### ISSUE TITLE
Технологический портал на все мои попытки выдает ошибку

### ISSUE THREAD

**Issue by Oleg-777** [vladk1m0/smevx-crypto#1]
Владимир, не могли вы прислать или выложить пример с исходным XML, чтобы можно было прогнать через  [https://smev3.gosuslugi.ru/portal/checkxmlform.jsp](https://smev3.gosuslugi.ru/portal/checkxmlform.jsp), версия схемы 1.2.
Складывется впечатление, что КриптоПРО JCP, не может работать со СМЭВ 3.
Написал в форум, может там что подскажут https://www.cryptopro.ru/forum2/default.aspx?g=posts&m=88989#post88989.

 За ранее, благодарен.

**Comment by vladk1m0** [comment]
@Oleg-777, доброго времени суток! Спасибо большое за обратную связь и ссылку https://smev3.gosuslugi.ru/portal/checkxmlform.jsp. Проверял подпись полученную методом ru.smevx.crypto.smev3.xmldsig.XmlDSignUtils.sign с помощью метода официальной библиотеки для СМЭВ 3 ru.voskhod.crypto.DigitalSignatureFactory.getDigitalSignatureProcessor().validateXMLDSigDetachedSignature(data, signature). Проверка проходила корректно), но судя по всему этого не достаточно. Буду разбираться, почему значение подписи полученное с помощью smevx-crypto не проходит проверку на https://smev3.gosuslugi.ru/portal/checkxmlform.jsp.

**Comment by vladk1m0** [comment]
@Oleg-777, залил в master фикс исправляющий ошибку. Теперь подписанный XML должен проходить проверку на портале  https://smev3.gosuslugi.ru/portal/checkxmlform.jsp.
